### ISSUE TITLE
Supporting aliases

### ISSUE THREAD

**Issue by markohlebar** [146BC/StyleKit#20]
What I mean is instead of repeating yourself by copy-pasting for instance `"HelveticaNeue-Bold:30.0"` you would instead have an alias `"bold30"`, or similarly `"blue" : "#000FFF"` . You could then have an aliases dict in the JSON that could be cross referenced at the start of parsing and aliases replaced with actual values.

**Comment by BernardGatt** [comment]
That is something i'm planning to add very soon, it's definitely a must have.

**Comment by BernardGatt** [comment]
We've placed this on our roadmap for version 1, another issue has been created https://github.com/146BC/StyleKit/issues/32

Thanks!
