### ISSUE TITLE
Demo project doesn't seem to work

### ISSUE THREAD

**Issue by grantkemp** [146BC/StyleKit#24]
Demo project just says no such file as Stylekit

**Comment by BernardGatt** [comment]
Please make sure you're opening StyleKit.xcworkspace

**Comment by grantkemp** [comment]
Hi @BernardGatt  - I tried that - but it doesn't seem to work.  I get below

![screen shot 2016-08-30 at 11 33 06](https://cloud.githubusercontent.com/assets/751115/18085984/99f80044-6ea5-11e6-9140-f3ab9e5805c2.jpg)

**Comment by BernardGatt** [comment]
You need to select the target on top where it says StyleKit > iPhone 6, click on StyleKit and change it to StyleKitDemo.

**Comment by grantkemp** [comment]
Thanks - it got it working.  I suggested some improvements to Readme to help others.
