### ISSUE TITLE
UIBarButtonItem support?

### ISSUE THREAD

**Issue by stevejcox** [146BC/StyleKit#26]
When trying to set the font on a UIBarButtonItem I constantly get unrecognized selector.
I'm sure I must be missing something obvious.

JSON code below

```
"UIBarButtonItem": {
        "titleTextAttributes": {
            "NSColor": "#99000000",
            "NSFont": "HelveticaNeue-Light:15.0"
        },
        "tintColor": "#000000"
}
```

Thanks for the library and suggestion,
Steve

**Comment by BernardGatt** [comment]
Since the titleTextAttributes for `UIBarButtonItem` requires a `:forState` parameter you'll need to send in a [state](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIControl_Class/#//apple_ref/c/tdef/UIControlState). 

This should do it!

``` javascript
    "UIBarButtonItem": {
        "titleTextAttributes:normal": {
            "NSColor": "#99000000",
            "NSFont": "HelveticaNeue-Light:15.0"
        },
        "tintColor": "#000000"
    }
```

Thanks for using the library :)
