### ISSUE TITLE
Providing a simple way to preview styles that can be copied via IOS10's cross device copying

### ISSUE THREAD

**Issue by grantkemp** [146BC/StyleKit#28]
One of the things that makes it hard to use Stylekit is that its difficult to preview styles and then to copy them without needing to retype. 

I added support for this via the Style Preview menu option in the Table in the PR referenced in this issue

**Comment by BernardGatt** [comment]
The best solution for this is to have live preview functionality, i'm currently working on the roadmap for version 1 maybe we can fit this in.

Thanks!

**Comment by BernardGatt** [comment]
We've placed this on our roadmap for version 1, another issue has been created #35 

Thanks!
