### ISSUE TITLE
Production ready

### ISSUE THREAD

**Issue by mikkelam** [146BC/StyleKit#37]
I'm considering using this project for an app, do you feel that it is production ready?

**Comment by BernardGatt** [comment]
We're currently building a couple of applications that use StyleKit which will soon be submitted to the App Store however if the current feature set is enough for your app, go ahead and use it.

[Version 1.0](https://medium.com/@BernardGatt/stylekit-68fa578ed07) will focus more on new features rather then fixing issues, we feel the version we have now is very stable.
