### ISSUE TITLE
Not available on CocoaPods

### ISSUE THREAD

**Issue by 0zguner** [146BC/StyleKit#47]
![screen shot 2017-06-08 at 16 24 47](https://user-images.githubusercontent.com/6003317/26930772-24d31a10-4c67-11e7-9711-f760168fe8a4.png)

**Comment by BernardGatt** [comment]
Yes, but it's available on our Spec repo, you just need to add the following to your Podfile.

```
source 'https://github.com/146BC/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
```
